name: pocket_doc
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  image_picker: ^0.8.7+4
  path_provider: ^2.0.0
  url_launcher:
  webview_flutter: ^4.9.0
  webview_flutter_android:
  webview_flutter_wkwebview:
  flutter_screenutil:
  get:
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  cc_essentials:
    git:
      url: https://github.com/DevMaan707/cc_essentials.git
      ref: v0.6.9
  get_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/images/appicon_img.png"
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true

  assets:
    # - lib/images/intro_img.png
    - lib/images/appicon_img.png
    - lib/images/intro_img.png
    - lib/images/intro2_img.png
    - lib/images/signin_img.png
    - lib/images/signup_img.png
    - lib/images/googleicon_img.png
    - lib/images/profile.png
